// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecgzlfqhdzzfikvbrwna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjZ3psZnFoZHp6ZmlrdmJyd25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzMjA0NjUsImV4cCI6MjA4Nzg5NjQ2NX0.UI9NKilTSaFgRwYvVKZUzfYdl20u8JBQLYDOLxalyVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});